# syntax=docker/dockerfile:1
FROM certbot/dns-cloudflare:v2.11.0
LABEL org.opencontainers.image.authors="asi@dbca.wa.gov.au"
LABEL org.opencontainers.image.source="https://github.com/dbca-wa/nginx-certbot"

RUN pip install certbot-dns-azure==2.5.0
