apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes-deployment.yaml --volumes hostPath
        kompose.service.type: nodeport
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
      name: nginx
    spec:
      ports:
        - name: "80"
          port: 80
          targetPort: 80
          nodePort: 30080
        - name: "443"
          port: 443
          targetPort: 443
          nodePort: 30443
      externalTrafficPolicy: "Local"
      selector:
        io.kompose.service: nginx
      type: NodePort
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes-deployment.yaml --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: certbot
      name: certbot
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: certbot
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o kubernetes-deployment.yaml --volumes hostPath
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: certbot
        spec:
          containers:
            - command:
                - /etc/letsencrypt/certbot-cron
              image: certbot/dns-cloudflare
              name: certbot
              resources: {}
              volumeMounts:
                - mountPath: /etc/letsencrypt
                  name: certbot-hostpath0
          restartPolicy: Always
          volumes:
            - hostPath:
                path: /var/nginx-etc/letsencrypt
              name: certbot-hostpath0
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes-deployment.yaml --volumes hostPath
        kompose.service.type: nodeport
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: nginx
      name: nginx
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: nginx
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o kubernetes-deployment.yaml --volumes hostPath
            kompose.service.type: nodeport
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: nginx
        spec:
          containers:
            - image: ghcr.io/dbca-wa/nginx-sigsci:1.19.6
              name: nginx
              ports:
                - containerPort: 80
                - containerPort: 443
              resources: {}
              volumeMounts:
                - mountPath: /etc/letsencrypt
                  name: nginx-hostpath0
                - mountPath: /etc/nginx
                  name: nginx-hostpath1
                - mountPath: /var/run
                  name: nginx-hostpath2
          restartPolicy: Always
          volumes:
            - hostPath:
                path: /var/nginx-etc/letsencrypt
              name: nginx-hostpath0
            - hostPath:
                path: /var/nginx-etc/nginx
              name: nginx-hostpath1
            - hostPath:
                path: /var/run/nginx-sigsci
              name: nginx-hostpath2
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o kubernetes-deployment.yaml --volumes hostPath
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: sigsci
      name: sigsci
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: sigsci
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o kubernetes-deployment.yaml --volumes hostPath
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: sigsci
        spec:
          containers:
            - args:
                - sigsci-agent
              image: ghcr.io/dbca-wa/nginx-sigsci:1.19.6
              name: sigsci
              resources: {}
              volumeMounts:
                - mountPath: /etc/sigsci
                  name: sigsci-hostpath0
                - mountPath: /var/run
                  name: sigsci-hostpath1
          restartPolicy: Always
          volumes:
            - hostPath:
                path: /var/nginx-etc/sigsci
              name: sigsci-hostpath0
            - hostPath:
                path: /var/run/nginx-sigsci
              name: sigsci-hostpath1
    status: {}
kind: List
metadata: {}

