apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -c --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 80
  - name: "8443"
    port: 8443
    targetPort: 443
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
